[package]
name = "example-reqwest-blocking"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.24", features = ["blocking", "json"] }
base64 = "0.22.1"
criipto-signatures-rs = { path="../..", features=["reqwest-blocking"] }
dotenv = "0.15.0"
anyhow = "1.0.100"
serde_json = "1.0.145"
